manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inorichi
      url-base: https://github.com/inorichi
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: carrefinho                            # <--- added this line for prospector
      url-base: https://github.com/carrefinho     # <--- anded this line for prospector
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: prospector-zmk-module                 # <--- anded this line for prospector
      remote: carrefinho                          # <--- anded this line for prospector
      revision: main                              # <--- anded this line for prospector
  self:
    path: config
